#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/42-Code-Odyssey ~/Documents ~/ -mindepth 1 -maxdepth 3 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    # Pas de tmux du tout, on crée et attache
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    # Crée en détaché si pas déjà existante
    tmux new-session -ds $selected_name -c $selected
fi

if [[ -n $TMUX ]]; then
    # Si dans tmux, switch client
    tmux switch-client -t $selected_name
else
    # Sinon, attache la session (depuis terminal normal)
    tmux attach-session -t $selected_name
fi

